import { Product } from "../types/product.types";

export const products: Product[] = [
  {
    id: "1",
    name: "Wireless Bluetooth Headphones with Noise Cancelling",
    subtitle: "Over-ear wireless headphones with deep bass and ANC",
    img: "/assets/products/prod1.webp",
    rating: 4.8,
    reviewCount: 120,
    price: 79.0,
    oldPrice: 159.99,
    originalPrice: 159.99,
    badge: "OFF",
    discountCount: 9,
    images: [
      {
        id: "1-main",
        url: "/assets/products/prod1.webp",
        alt: "Wireless Bluetooth Headphones with Noise Cancelling front view",
      },
      {
        id: "2-main",
        url: "/assets/products/productfill1.webp",
        alt: "product fill Slider",
      },
      {
        id: "3-main",
        url: "/assets/products/productfill2.webp",
        alt: "product fill 2 slider",
      },
    ],
    colors: [
      { id: "black", name: "Black", hex: "#020617" },
      { id: "blue", name: "Blue", hex: "#1D4ED8" },
      { id: "pink", name: "Pink", hex: "#EC4899" },
    ],
    variants: [
      { id: "1-black", colorId: "black", size: "Standard", stock: 20 },
      { id: "1-blue", colorId: "blue", size: "Standard", stock: 10 },
      { id: "1-pink", colorId: "pink", size: "Standard", stock: 5 },
    ],
    description:
      "Premium wireless headphones with active noise cancelling, soft ear cushions, and all-day battery life. Perfect for travel, work, and music on the go.",
    features: [
      "Active Noise Cancelling with transparency mode",
      "Up to 30 hours of battery life on a single charge",
      "Bluetooth 5.2 with stable, low-latency connection",
      "Built-in microphone for clear calls",
    ],
    specs: {
      Category: "Audio",
      Connectivity: "Bluetooth 5.2",
      "Battery life": "30 hours",
      Weight: "250 g",
      Warranty: "1 year",
    },
    badges: ["Best Seller", "Free Shipping"],
  },
  {
    id: "2",
    name: "Smart Watch Series 8 - Fitness Tracker",
    subtitle: "Advanced fitness tracking with heart-rate monitoring",
    img: "/assets/products/prod2.webp",
    rating: 4.9,
    reviewCount: 120,
    price: 299.0,
    oldPrice: undefined,
    originalPrice: null,
    badge: "NEW",
    discountCount: null,
    images: [
      {
        id: "1-main",
        url: "/assets/products/prod2.webp",
        alt: "Smart Watch Series 8 with fitness stats on screen",
      },
      {
        id: "2-main",
        url: "/assets/products/productfill1.webp",
        alt: "product fill Slider",
      },
      {
        id: "3-main",
        url: "/assets/products/productfill2.webp",
        alt: "product fill 2 slider",
      },
    ],
    colors: [
      { id: "black", name: "Black", hex: "#020617" },
      { id: "blue", name: "Blue", hex: "#1D4ED8" },
      { id: "pink", name: "Pink", hex: "#EC4899" },
    ],
    variants: [
      { id: "1-black", colorId: "black", size: "Standard", stock: 20 },
      { id: "1-blue", colorId: "blue", size: "Standard", stock: 10 },
      { id: "1-pink", colorId: "pink", size: "Standard", stock: 5 },
    ],
    description:
      "Next-generation smartwatch with advanced health tracking, customizable watch faces, and all-day battery life. Stay connected while tracking your workouts and daily activity.",
    features: [
      "24/7 heart rate and SpO2 monitoring",
      "Built-in GPS for accurate outdoor tracking",
      "Water resistant design for swimming and workouts",
      "Receive notifications, calls, and messages on your wrist",
    ],
    specs: {
      Category: "Wearables",
      "Display size": '1.8"',
      "Water resistance": "IP68",
      "Battery life": "Up to 2 days",
      Compatibility: "iOS & Android",
    },
    badges: ["New Arrival"],
  },
  {
    id: "3",
    name: "Premium Leather Backpack - Multiple Compartments",
    subtitle: "Stylish everyday backpack for work and travel",
    img: "/assets/products/prod3.webp",
    rating: 4.7,
    reviewCount: 120,
    price: 299.0,
    oldPrice: undefined,
    originalPrice: null,
    badge: "HOT",
    discountCount: null,
    images: [
      {
        id: "1-main",
        url: "/assets/products/prod3.webp",
        alt: "Premium leather backpack standing on a desk",
      },
      {
        id: "2-main",
        url: "/assets/products/productfill1.webp",
        alt: "product fill Slider",
      },
      {
        id: "3-main",
        url: "/assets/products/productfill2.webp",
        alt: "product fill 2 slider",
      },
    ],
    colors: [
      { id: "black", name: "Black", hex: "#020617" },
      { id: "blue", name: "Blue", hex: "#1D4ED8" },
      { id: "pink", name: "Pink", hex: "#EC4899" },
    ],
    variants: [
      { id: "1-black", colorId: "black", size: "Standard", stock: 20 },
      { id: "1-blue", colorId: "blue", size: "Standard", stock: 10 },
      { id: "1-pink", colorId: "pink", size: "Standard", stock: 5 },
    ],
    description:
      "High-quality leather backpack with multiple organized compartments, perfect for carrying your laptop, documents, and daily essentials.",
    features: [
      'Dedicated padded laptop compartment up to 15.6"',
      "Multiple internal pockets for organization",
      "Adjustable padded shoulder straps for comfort",
      "Durable zippers and reinforced stitching",
    ],
    specs: {
      Category: "Bags & Accessories",
      Material: "Genuine leather",
      Capacity: "20 L",
      "Laptop pocket": 'Up to 15.6"',
      Color: "Brown",
    },
    badges: ["Trending", "Limited Stock"],
  },
  {
    id: "4",
    name: "Ultra HD 4K Action Camera with Accessories",
    subtitle: "Capture every adventure in crisp 4K",
    img: "/assets/products/prod4.webp",
    rating: 4.6,
    reviewCount: 120,
    price: 299.0,
    oldPrice: undefined,
    originalPrice: null,
    badge: "NEW",
    discountCount: null,
    images: [
      {
        id: "4-main",
        url: "/assets/products/prod4.webp",
        alt: "Ultra HD 4K action camera with accessories",
      },
      {
        id: "2-main",
        url: "/assets/products/productfill1.webp",
        alt: "product fill Slider",
      },
      {
        id: "3-main",
        url: "/assets/products/productfill2.webp",
        alt: "product fill 2 slider",
      },
    ],
    colors: [
      { id: "black", name: "Black", hex: "#020617" },
      { id: "blue", name: "Blue", hex: "#1D4ED8" },
      { id: "pink", name: "Pink", hex: "#EC4899" },
    ],
    variants: [
      { id: "1-black", colorId: "black", size: "Standard", stock: 20 },
      { id: "1-blue", colorId: "blue", size: "Standard", stock: 10 },
      { id: "1-pink", colorId: "pink", size: "Standard", stock: 5 },
    ],
    description:
      "Rugged 4K action camera with wide-angle lens, waterproof housing, and a full set of mounts for biking, surfing, and more.",
    features: [
      "4K UHD video recording with wide-angle lens",
      "Waterproof housing up to 30 m",
      "Multiple mounting accessories included",
      "Built-in Wi-Fi for quick sharing",
    ],
    specs: {
      Category: "Cameras & Photo",
      Resolution: "4K UHD",
      "Waterproof rating": "Up to 30 m with case",
      "Battery life": "Up to 90 minutes",
      Connectivity: "Wi-Fi",
    },
    badges: ["New Arrival", "Adventure Ready"],
  },
  {
    id: "5",
    name: "Minimalist Desk Lamp with USB Charging Port",
    subtitle: "Modern LED lamp for your workspace",
    img: "/assets/products/prod5.webp",
    rating: 4.5,
    reviewCount: 120,
    price: 299.0,
    oldPrice: undefined,
    originalPrice: null,
    badge: "HOT",
    discountCount: null,
    images: [
      {
        id: "5-main",
        url: "/assets/products/prod5.webp",
        alt: "Minimalist desk lamp on a wooden table",
      },
      {
        id: "2-main",
        url: "/assets/products/productfill1.webp",
        alt: "product fill Slider",
      },
      {
        id: "3-main",
        url: "/assets/products/productfill2.webp",
        alt: "product fill 2 slider",
      },
    ],
    colors: [
      { id: "black", name: "Black", hex: "#020617" },
      { id: "blue", name: "Blue", hex: "#1D4ED8" },
      { id: "pink", name: "Pink", hex: "#EC4899" },
    ],
    variants: [
      { id: "1-black", colorId: "black", size: "Standard", stock: 20 },
      { id: "1-blue", colorId: "blue", size: "Standard", stock: 10 },
      { id: "1-pink", colorId: "pink", size: "Standard", stock: 5 },
    ],
    description:
      "Sleek, minimalist LED desk lamp with adjustable brightness and a built-in USB port to charge your devices while you work.",
    features: [
      "3 adjustable brightness levels",
      "Built-in USB charging port",
      "Energy-efficient LED lighting",
      "Flexible neck for easy repositioning",
    ],
    specs: {
      Category: "Home & Office",
      "Light source": "LED",
      "Power input": "USB",
      "Brightness levels": "3 modes",
      Color: "White",
    },
    badges: ["Popular Choice"],
  },
  {
    id: "6",
    name: "Stainless Steel Water Bottle - Insulated 32oz",
    subtitle: "Keeps drinks cold for up to 24 hours",
    img: "/assets/products/prod6.webp",
    rating: 4.8,
    reviewCount: 120,
    price: 299.0,
    oldPrice: undefined,
    originalPrice: null,
    badge: "OFF",
    discountCount: 15,
    images: [
      {
        id: "6-main",
        url: "/assets/products/prod6.webp",
        alt: "Stainless steel insulated water bottle",
      },
      {
        id: "2-main",
        url: "/assets/products/productfill1.webp",
        alt: "product fill Slider",
      },
      {
        id: "3-main",
        url: "/assets/products/productfill2.webp",
        alt: "product fill 2 slider",
      },
    ],
    colors: [
      { id: "black", name: "Black", hex: "#020617" },
      { id: "blue", name: "Blue", hex: "#1D4ED8" },
      { id: "pink", name: "Pink", hex: "#EC4899" },
    ],
    variants: [
      { id: "1-black", colorId: "black", size: "Standard", stock: 20 },
      { id: "1-blue", colorId: "blue", size: "Standard", stock: 10 },
      { id: "1-pink", colorId: "pink", size: "Standard", stock: 5 },
    ],
    description:
      "Durable stainless steel insulated bottle that keeps your drinks cold or hot for hours. Ideal for workouts, travel, and everyday use.",
    features: [
      "Double-wall vacuum insulation",
      "Sweat-free exterior finish",
      "Leak-proof lid with carry handle",
      "BPA-free materials",
    ],
    specs: {
      Category: "Outdoors & Travel",
      Capacity: "32 oz (950 ml)",
      Material: "Stainless steel",
      Insulation: "Double-wall vacuum",
      "Dishwasher safe": "Hand wash recommended",
    },
    badges: ["Limited Offer"],
  },
  {
    id: "7",
    name: "Mechanical Gaming Keyboard - RGB Backlit",
    subtitle: "Responsive mechanical keys with customizable lighting",
    img: "/assets/products/prod7.webp",
    rating: 4.9,
    reviewCount: 120,
    price: 299.0,
    oldPrice: undefined,
    originalPrice: null,
    badge: "OFF",
    discountCount: 20,
    images: [
      {
        id: "7-main",
        url: "/assets/products/prod7.webp",
        alt: "Mechanical gaming keyboard with RGB lighting",
      },
      {
        id: "2-main",
        url: "/assets/products/productfill1.webp",
        alt: "product fill Slider",
      },
      {
        id: "3-main",
        url: "/assets/products/productfill2.webp",
        alt: "product fill 2 slider",
      },
    ],
    colors: [
      { id: "black", name: "Black", hex: "#020617" },
      { id: "blue", name: "Blue", hex: "#1D4ED8" },
      { id: "pink", name: "Pink", hex: "#EC4899" },
    ],
    variants: [
      { id: "1-black", colorId: "black", size: "Standard", stock: 20 },
      { id: "1-blue", colorId: "blue", size: "Standard", stock: 10 },
      { id: "1-pink", colorId: "pink", size: "Standard", stock: 5 },
    ],
    description:
      "High-performance mechanical gaming keyboard with customizable RGB backlighting and anti-ghosting keys for competitive play.",
    features: [
      "Mechanical switches with tactile feedback",
      "Per-key RGB backlighting",
      "Full anti-ghosting and N-key rollover",
      "Detachable USB cable",
    ],
    specs: {
      Category: "Computer Accessories",
      Switches: "Mechanical",
      "Key rollover": "N-key",
      Backlighting: "Per-key RGB",
      Layout: "Full-size",
    },
    badges: ["Gamer Favorite"],
  },
  {
    id: "8",
    name: "Wireless Bluetooth Headphones with Noise Cancelling",
    subtitle: "Compact edition with foldable design",
    img: "/assets/products/prod1.webp",
    rating: 4.8,
    reviewCount: 120,
    price: 79.0,
    oldPrice: 159.99,
    originalPrice: 159.99,
    badge: "OFF",
    discountCount: 9,
    images: [
      {
        id: "8-main",
        url: "/assets/products/prod1.webp",
        alt: "Wireless Bluetooth headphones folded on a table",
      },
      {
        id: "2-main",
        url: "/assets/products/productfill1.webp",
        alt: "product fill Slider",
      },
      {
        id: "3-main",
        url: "/assets/products/productfill2.webp",
        alt: "product fill 2 slider",
      },
    ],
    colors: [
      { id: "black", name: "Black", hex: "#020617" },
      { id: "blue", name: "Blue", hex: "#1D4ED8" },
      { id: "pink", name: "Pink", hex: "#EC4899" },
    ],
    variants: [
      { id: "1-black", colorId: "black", size: "Standard", stock: 20 },
      { id: "1-blue", colorId: "blue", size: "Standard", stock: 10 },
      { id: "1-pink", colorId: "pink", size: "Standard", stock: 5 },
    ],
    description:
      "Lightweight, foldable wireless headphones with powerful noise cancelling and clear audio for everyday listening.",
    features: [
      "Foldable design for easy storage",
      "Active noise cancelling",
      "Comfortable padded earcups",
      "Built-in controls on the earcup",
    ],
    specs: {
      Category: "Audio",
      Connectivity: "Bluetooth 5.0",
      "Battery life": "25 hours",
      Weight: "230 g",
      Warranty: "1 year",
    },
    badges: ["Best Seller"],
  },
  {
    id: "9",
    name: "Smart Watch Series 8 - Fitness Tracker",
    subtitle: "Smartwatch with advanced health features",
    img: "/assets/products/prod2.webp",
    rating: 4.9,
    reviewCount: 120,
    price: 299.0,
    oldPrice: undefined,
    originalPrice: null,
    badge: "NEW",
    discountCount: null,
    images: [
      {
        id: "9-main",
        url: "/assets/products/prod2.webp",
        alt: "Smart watch showing health metrics",
      },
      {
        id: "2-main",
        url: "/assets/products/productfill1.webp",
        alt: "product fill Slider",
      },
      {
        id: "3-main",
        url: "/assets/products/productfill2.webp",
        alt: "product fill 2 slider",
      },
    ],
    colors: [
      { id: "black", name: "Black", hex: "#020617" },
      { id: "blue", name: "Blue", hex: "#1D4ED8" },
      { id: "pink", name: "Pink", hex: "#EC4899" },
    ],
    variants: [
      { id: "1-black", colorId: "black", size: "Standard", stock: 20 },
      { id: "1-blue", colorId: "blue", size: "Standard", stock: 10 },
      { id: "1-pink", colorId: "pink", size: "Standard", stock: 5 },
    ],
    description:
      "Feature-rich smartwatch designed to help you stay active, healthy, and connected throughout the day.",
    features: [
      "Advanced sleep and stress tracking",
      "Customizable watch faces",
      "Music control and playback",
      "Fast magnetic charging",
    ],
    specs: {
      Category: "Wearables",
      "Display type": "AMOLED",
      "Water resistance": "IP68",
      "Battery life": "Up to 36 hours",
      Sensors: "Heart rate, SpO2, accelerometer",
    },
    badges: ["New Arrival"],
  },
  {
    id: "10",
    name: "Premium Leather Backpack - Multiple Compartments",
    subtitle: "Versatile leather backpack for work or school",
    img: "/assets/products/prod3.webp",
    rating: 4.7,
    reviewCount: 120,
    price: 299.0,
    oldPrice: undefined,
    originalPrice: null,
    badge: "HOT",
    discountCount: null,
    images: [
      {
        id: "10-main",
        url: "/assets/products/prod3.webp",
        alt: "Premium leather backpack on a chair",
      },
      {
        id: "2-main",
        url: "/assets/products/productfill1.webp",
        alt: "product fill Slider",
      },
      {
        id: "3-main",
        url: "/assets/products/productfill2.webp",
        alt: "product fill 2 slider",
      },
    ],
    colors: [
      { id: "black", name: "Black", hex: "#020617" },
      { id: "blue", name: "Blue", hex: "#1D4ED8" },
      { id: "pink", name: "Pink", hex: "#EC4899" },
    ],
    variants: [
      { id: "1-black", colorId: "black", size: "Standard", stock: 20 },
      { id: "1-blue", colorId: "blue", size: "Standard", stock: 10 },
      { id: "1-pink", colorId: "pink", size: "Standard", stock: 5 },
    ],
    description:
      "Elegant leather backpack with a minimalist design, perfect for commuting, school, or weekend trips.",
    features: [
      "Spacious main compartment with zipper closure",
      "Hidden pocket for valuables",
      "Comfortable padded straps",
      "High-quality leather finish",
    ],
    specs: {
      Category: "Bags & Accessories",
      Material: "Genuine leather",
      Capacity: "22 L",
      "Laptop pocket": 'Up to 15"',
      Color: "Black",
    },
    badges: ["Trending"],
  },
  {
    id: "11",
    name: "Ultra HD 4K Action Camera with Accessories",
    subtitle: "Compact action camera for outdoor adventures",
    img: "/assets/products/prod4.webp",
    rating: 4.6,
    reviewCount: 120,
    price: 299.0,
    oldPrice: undefined,
    originalPrice: null,
    badge: "NEW",
    discountCount: null,
    images: [
      {
        id: "11-main",
        url: "/assets/products/prod4.webp",
        alt: "4K action camera mounted on a helmet",
      },
      {
        id: "2-main",
        url: "/assets/products/productfill1.webp",
        alt: "product fill Slider",
      },
      {
        id: "3-main",
        url: "/assets/products/productfill2.webp",
        alt: "product fill 2 slider",
      },
    ],
    colors: [
      { id: "black", name: "Black", hex: "#020617" },
      { id: "blue", name: "Blue", hex: "#1D4ED8" },
      { id: "pink", name: "Pink", hex: "#EC4899" },
    ],
    variants: [
      { id: "1-black", colorId: "black", size: "Standard", stock: 20 },
      { id: "1-blue", colorId: "blue", size: "Standard", stock: 10 },
      { id: "1-pink", colorId: "pink", size: "Standard", stock: 5 },
    ],
    description:
      "Lightweight action camera with 4K recording, slow-motion modes, and a variety of mounts to capture every moment.",
    features: [
      "4K video recording at 60 fps",
      "Slow-motion capture modes",
      "Includes helmet and handlebar mounts",
      "Mobile app for live preview and control",
    ],
    specs: {
      Category: "Cameras & Photo",
      Resolution: "4K @ 60 fps",
      "Waterproof rating": "Up to 30 m with housing",
      "Field of view": "170° wide-angle",
      Storage: "microSD (up to 128 GB)",
    },
    badges: ["New Arrival", "Adventure Ready"],
  },
  {
    id: "12",
    name: "Minimalist Desk Lamp with USB Charging Port",
    subtitle: "Slim LED lamp for modern desks",
    img: "/assets/products/prod5.webp",
    rating: 4.5,
    reviewCount: 120,
    price: 299.0,
    oldPrice: undefined,
    originalPrice: null,
    badge: "HOT",
    discountCount: null,
    images: [
      {
        id: "12-main",
        url: "/assets/products/prod5.webp",
        alt: "Minimalist LED desk lamp near a laptop",
      },
      {
        id: "2-main",
        url: "/assets/products/productfill1.webp",
        alt: "product fill Slider",
      },
      {
        id: "3-main",
        url: "/assets/products/productfill2.webp",
        alt: "product fill 2 slider",
      },
    ],
    colors: [
      { id: "black", name: "Black", hex: "#020617" },
      { id: "blue", name: "Blue", hex: "#1D4ED8" },
      { id: "pink", name: "Pink", hex: "#EC4899" },
    ],
    variants: [
      { id: "1-black", colorId: "black", size: "Standard", stock: 20 },
      { id: "1-blue", colorId: "blue", size: "Standard", stock: 10 },
      { id: "1-pink", colorId: "pink", size: "Standard", stock: 5 },
    ],
    description:
      "Modern desk lamp with adjustable arm, soft LED lighting, and integrated USB charging for your devices.",
    features: [
      "Touch controls for brightness",
      "Adjustable arm and head",
      "Integrated USB charging port",
      "Low-glare, eye-friendly light",
    ],
    specs: {
      Category: "Home & Office",
      "Light source": "LED",
      "Power input": "USB or wall adapter",
      "Brightness levels": "Touch adjustable",
      Color: "Black",
    },
    badges: ["Staff Pick"],
  },
  {
    id: "13",
    name: "Stainless Steel Water Bottle - Insulated 32oz",
    subtitle: "Durable bottle for gym and outdoor use",
    img: "/assets/products/prod6.webp",
    rating: 4.8,
    reviewCount: 120,
    price: 299.0,
    oldPrice: undefined,
    originalPrice: null,
    badge: "OFF",
    discountCount: 15,
    images: [
      {
        id: "13-main",
        url: "/assets/products/prod6.webp",
        alt: "Insulated stainless steel water bottle on a bench",
      },
      {
        id: "2-main",
        url: "/assets/products/productfill1.webp",
        alt: "product fill Slider",
      },
      {
        id: "3-main",
        url: "/assets/products/productfill2.webp",
        alt: "product fill 2 slider",
      },
    ],
    colors: [
      { id: "black", name: "Black", hex: "#020617" },
      { id: "blue", name: "Blue", hex: "#1D4ED8" },
      { id: "pink", name: "Pink", hex: "#EC4899" },
    ],
    variants: [
      { id: "1-black", colorId: "black", size: "Standard", stock: 20 },
      { id: "1-blue", colorId: "blue", size: "Standard", stock: 10 },
      { id: "1-pink", colorId: "pink", size: "Standard", stock: 5 },
    ],
    description:
      "Large-capacity insulated stainless steel bottle that keeps beverages cold up to 24 hours and hot up to 12 hours.",
    features: [
      "Wide mouth for easy cleaning and ice cubes",
      "Leak-proof screw-on lid",
      "Durable powder-coat finish",
      "Fits most cup holders",
    ],
    specs: {
      Category: "Outdoors & Travel",
      Capacity: "32 oz (950 ml)",
      Insulation: "Double-wall vacuum",
      Material: "Stainless steel",
      "BPA free": "Yes",
    },
    badges: ["Limited Offer"],
  },
  {
    id: "14",
    name: "Mechanical Gaming Keyboard - RGB Backlit",
    subtitle: "Full-size gaming keyboard with macro support",
    img: "/assets/products/prod7.webp",
    rating: 4.9,
    reviewCount: 120,
    price: 299.0,
    oldPrice: undefined,
    originalPrice: null,
    badge: "OFF",
    discountCount: 20,
    images: [
      {
        id: "14-main",
        url: "/assets/products/prod7.webp",
        alt: "RGB mechanical gaming keyboard on a gaming desk",
      },
      {
        id: "2-main",
        url: "/assets/products/productfill1.webp",
        alt: "product fill Slider",
      },
      {
        id: "3-main",
        url: "/assets/products/productfill2.webp",
        alt: "product fill 2 slider",
      },
    ],
    colors: [
      { id: "black", name: "Black", hex: "#020617" },
      { id: "blue", name: "Blue", hex: "#1D4ED8" },
      { id: "pink", name: "Pink", hex: "#EC4899" },
    ],
    variants: [
      { id: "1-black", colorId: "black", size: "Standard", stock: 20 },
      { id: "1-blue", colorId: "blue", size: "Standard", stock: 10 },
      { id: "1-pink", colorId: "pink", size: "Standard", stock: 5 },
    ],
    description:
      "RGB mechanical gaming keyboard with programmable macros, durable switches, and a solid frame for intense gaming sessions.",
    features: [
      "Programmable macro keys",
      "Customizable RGB lighting effects",
      "Durable mechanical switches rated for 50M presses",
      "Detachable wrist rest",
    ],
    specs: {
      Category: "Computer Accessories",
      Switches: "Mechanical",
      Backlighting: "RGB",
      Layout: "Full-size with numpad",
      Connectivity: "USB-C wired",
    },
    badges: ["Gamer Favorite", "On Sale"],
  },
];
